# setup

In [ ]:
!pip install -U datascience ipytest rich

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 237 kB 5.1 MB/s 
     |████████████████████████████████| 298 kB 12.0 MB/s 
     |████████████████████████████████| 51 kB 3.0 MB/s 
     |████████████████████████████████| 1.6 MB 53.3 MB/s 
  Attempting uninstall: pluggy
    Found existing installation: pluggy 0.7.1
    Uninstalling pluggy-0.7.1:
      Successfully uninstalled pluggy-0.7.1
  Attempting uninstall: pytest
    Found existing installation: pytest 3.6.4
    Uninstalling pytest-3.6.4:
      Successfully uninstalled pytest-3.6.4


In [ ]:
from __future__ import annotations
import math
import ipytest
import numpy as np
import pandas as pd
from pytest import approx

ipytest.autoconfig()

# test

<h1> หาผลรวมในลิสต์

จงสร้างฟังก์ชั่นให้สมบูรณ์โดยที่จะรับค่าลิสต์เข้าไปในฟังก์ชั่นและนำข้อมูลทั้งหมดในลิสต์มาบวกกันและreturnผลออกไป

In [ ]:
def sumlist(arr: list[int]):
  # เขียนโค้ดตรงนี้
  return 0

In [ ]:
%%ipytest -qqs
def test_count_even():
    assert sumlist([1, 2, 3, 4, 5]) == 15
    assert sumlist([1, 3, 5, 7]) == 16
    assert sumlist([2, 4, 8, 16, 32]) == 62
    assert sumlist([]) == 0
    print("==== Test OK ====")

==== Test OK ====
.


<h1> FizzBuzz

จงเขียนฟังก์ชัน `fizzbuzz` ที่รับlist
โดย
- สร้างlistใหม่ขึ้นมาอันนึง
- ถ้า listที่ได้รับมามีเลขที่ หารด้วย 2 ลงตัว แต่หารด้วย 3 ไม่ลงตัว ให้เก็บค่า string ว่า `"fizz"`ในlistใหม่
- ถ้า listที่ได้รับมามีเลขที่ หารด้วย 3 ลงตัว แต่หารด้วย 2 ไม่ลงตัว ให้เก็บค่า string ว่า `"buzz"`ในlistใหม่
- ถ้า listที่ได้รับมามีเลขที่ หารด้วยทั้ง 2 และ 3 ลงตัวทั้งคู่ ให้เก็บค่า string ว่า `"fizzbuzz"`ในlistใหม่
- นอกเหนือจากเงื่อนไขข้างต้น ให้เก็บค่า เลขนั้นในlistใหม่
จากนั้นให้return listที่สร้างและเก็บค่าดังกล่าวออกไป

(**คำใบ้:** ลองใช้ `if`, `elif`, และ `else` ภายในฟังก์ชัน `fizzbuzz`)

In [ ]:
def fizzbuzz(arr: list[int]):
  # เขียนโค้ดตรงนี้ 
  return 0

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[1, 'fizz', 'buzz', 'fizz', 5, 'fizzbuzz', 7, 'fizz', 'buzz', 'fizz', 11, 'fizzbuzz', 13, 'fizz', 'buzz', 'fizz', 17, 'fizzbuzz', 19]


In [ ]:
# ตรวจคำตอบ
%%ipytest -qqs
def test_calmenu():
    assert fizzbuzz(range(1,20)) == [1,'fizz','buzz','fizz',5,'fizzbuzz',7,'fizz','buzz','fizz',11,'fizzbuzz',13,'fizz','buzz','fizz',17,'fizzbuzz',19]
    print("==== Test OK ====")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
==== Test OK ====
.


<h1>หา Prefix ทั้งหมดที่เป็นไปได้

--- 

 จงเติมฟังก์ชัน `all_prefixes` ให้สมบูรณ์ เพื่อคำนวณหาลิสต์ของ Prefix ทั้งหมดของสตริงที่กำหนดให้ 

---
ตัวอย่าง 
ยกตัวอย่างเช่น สตริง `"Hello, World!"` ประกอบไปด้วย Prefix ดังต่อไปนี้ โดยให้returnออกมาเป็นลิสต์
- [
- `""`
- `"H"`
- `"He"`
- `"Hel"`
- `"Hell"`
- `"Hello"`
- `"Hello,"`
- `"Hello, "`
- `"Hello, W"`
- `"Hello, Wo"`
- `"Hello, Wor"`
- `"Hello, Worl"`
- `"Hello, World"`
- `"Hello, World!"` 
- ]


In [ ]:
def all_prefixes(s: str) -> list[str]:
    # เขียนโค้ดของคุณตรงนี้

    return 0

I
R
E
M


['IREM']

In [ ]:
%%ipytest -qqs
def test_all_prefixes():
    assert all_prefixes("Hello, World!") == [
        "",
        "H",
        "He",
        "Hel",
        "Hell",
        "Hello",
        "Hello,",
        "Hello, ",
        "Hello, W",
        "Hello, Wo",
        "Hello, Wor",
        "Hello, Worl",
        "Hello, World",
        "Hello, World!",
    ]
    assert all_prefixes("APPLES") == ["", "A", "AP", "APP", "APPL", "APPLE", "APPLES"]
    assert all_prefixes("👨‍🦱") == ["", "👨", "👨\u200d", "👨\u200d🦱"]
    assert all_prefixes("") == [""]
    print("==== Test OK ====")

<h2>สับเปลี่ยนมิติ


ให้สร้างฟังกชั่นสับเปลี่ยนมิติให้เรียบร้อย ซึ่งรับค่าสามค่า คือ arr แล้วก็ shapeที่ต้องการเปลี่ยน โดยมี x,y
โดยถ้าสามารถreshapeได้ ให้returnค่าออกมาเป็นarrayที่reshapeแล้ว แต่ถ้าทำไม่ได้ให้return 'please try again'

In [ ]:
def changeD(arr: list[int],x,y):
  # เขียนโค้ดตรงนี้
  return 0

In [ ]:
# ตรวจคำตอบ
%%ipytest -qqs
def test_calmenu():
    assert str(changeD(np.array([1,2,3,4,5,6,7,8]),2,4)) == str(np.array([[1, 2, 3, 4],[5, 6, 7, 8]]))
    assert str(changeD(np.array([1,2,3,4,5,6,7,8,9]),3,3)) == str(np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]))
    assert str(changeD(np.array([1,2,3,4,5,6,7,8,9]),4,3)) == 'please try again'
    print("==== Test OK ====")

==== Test OK ====
.


<h1>ค่าเฉลี่ยของแต่ละคอลัมน์ของ a (ซึ่งมีขนาด  3×3 ) มีค่าเท่าใด?

In [ ]:
def findmean(a: list[int]):
  return 0
  

[1 2 3]
[4 5 6]
[7 8 9]


'None'

In [ ]:
# ตรวจคำตอบ
%%ipytest -qqs
def test_calmenu():
    assert str(findmean(np.array([[1,2,3],[4,5,6],[7,8,9]]))) == str(np.array([4., 5., 6.]))
    print("==== Test OK ====")

==== Test OK ====
.
